apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hg6207ibf-nodejs
  janus-idp.io/tekton: hg6207ibf-nodejs
  backstage.io/kubernetes-id: hg6207ibf-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hg6207ibf-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
